-- 删除触发器及其对应函数
DROP TRIGGER IF EXISTS check_team_member_exists ON indvuser_belong_team;
DROP FUNCTION IF EXISTS check_team_member_exists_func;
DROP TRIGGER IF EXISTS check_member_role_match ON indvuser_belong_team;
DROP FUNCTION IF EXISTS check_member_role_match_func;
DROP TRIGGER IF EXISTS check_user_in_individual_users ON indvuser_belong_org;
DROP FUNCTION IF EXISTS check_user_in_individual_users_func;
DROP TRIGGER IF EXISTS insert_new_user ON users;
DROP FUNCTION IF EXISTS insert_new_user_func;
DROP TRIGGER IF EXISTS update_user_attributes ON users;
DROP FUNCTION IF EXISTS update_user_attributes_func;
DROP TRIGGER IF EXISTS check_password_before_update ON users;
DROP FUNCTION IF EXISTS check_password_before_update_func;
DROP TRIGGER IF EXISTS delete_user_data ON users;
DROP FUNCTION IF EXISTS delete_user_data_func;
DROP TRIGGER IF EXISTS update_installation_and_bill ON users_install_app;
DROP FUNCTION IF EXISTS update_installation_and_bill_func;
DROP TRIGGER IF EXISTS update_action_stars ON users_star_action;
DROP FUNCTION IF EXISTS update_action_stars_func;
DROP TRIGGER IF EXISTS update_action_unstars ON users_star_action;
DROP FUNCTION IF EXISTS update_action_unstars_func;
DROP TRIGGER IF EXISTS check_unique_role_in_team ON indvuser_belong_team;
DROP FUNCTION IF EXISTS check_unique_role_in_team_func;
DROP TRIGGER IF EXISTS check_team_member_limit ON indvuser_belong_team;
DROP FUNCTION IF EXISTS check_team_member_limit_func;
DROP TRIGGER IF EXISTS delete_related_user_data ON users;
DROP FUNCTION IF EXISTS delete_related_user_data_func;
DROP TRIGGER IF EXISTS check_unique_admin_in_organization ON indvuser_belong_team;
DROP FUNCTION IF EXISTS check_unique_admin_in_organization_func;
DROP TRIGGER IF EXISTS increment_app_version ON app;
DROP FUNCTION IF EXISTS increment_app_version_func;

-- 删除视图
DROP VIEW IF EXISTS user_follower_count;
DROP VIEW IF EXISTS user_following_count;
DROP VIEW IF EXISTS user_star_count;
DROP VIEW IF EXISTS user_given_stars;
DROP VIEW IF EXISTS user_star_statistics;
DROP VIEW IF EXISTS user_follower_statistics;
DROP VIEW IF EXISTS repository_star_statistics;
DROP VIEW IF EXISTS repository_star_statistics_timeframe;
DROP VIEW IF EXISTS repository_fork_statistics;
DROP VIEW IF EXISTS repository_fork_statistics_timeframe;
DROP VIEW IF EXISTS repository_watch_statistics;
DROP VIEW IF EXISTS repository_watch_statistics_timeframe;
DROP VIEW IF EXISTS repository_view_statistics;
DROP VIEW IF EXISTS repository_view_statistics_timeframe;

-- 删除表
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS individualuser;
DROP TABLE IF EXISTS organization;
DROP TABLE IF EXISTS indvuser_belong_org;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS indvuser_belong_team;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS user_join_events;
DROP TABLE IF EXISTS app;
DROP TABLE IF EXISTS action;
DROP TABLE IF EXISTS users_install_app;
DROP TABLE IF EXISTS users_install_action;
DROP TABLE IF EXISTS org_develop_app;
DROP TABLE IF EXISTS user_contribute_action;
DROP TABLE IF EXISTS user1_follow_user2;
DROP TABLE IF EXISTS user1_star_user2;
DROP TABLE IF EXISTS repositories;
DROP TABLE IF EXISTS topic;
DROP TABLE IF EXISTS repositories_match_topic;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS repositories_match_collections;
DROP TABLE IF EXISTS releases;
DROP TABLE IF EXISTS packages;
DROP TABLE IF EXISTS code;
DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS pull_requests;
DROP TABLE IF EXISTS user_view_repositories;
DROP TABLE IF EXISTS user_fork_repositories;
DROP TABLE IF EXISTS user_star_repositories;
DROP TABLE IF EXISTS user_watch_repositories;
DROP TABLE IF EXISTS user_develop_repositories;
DROP TABLE IF EXISTS user_respond_issue_repositories;
DROP TABLE IF EXISTS user_fileschangedin_repositories;
DROP TABLE IF EXISTS users_star_topic;
DROP TABLE IF EXISTS users_star_collections;
DROP TABLE IF EXISTS users_star_action;
DROP TABLE IF EXISTS popular_repositories;
DROP TABLE IF EXISTS popular_users;